In [1]:
import autograd.numpy as np   # Thinly-wrapped version of Numpy
from autograd import grad

In [2]:
def taylor_sine(x):  # Taylor approximation to sine function
    ans = currterm = x
    i = 0
    while np.abs(currterm) > 0.001:
        currterm = -currterm * x**2 / ((2 * i + 3) * (2 * i + 2))
        ans = ans + currterm
        i += 1
    return ans

In [5]:
grad_sine = grad(taylor_sine)
print("Gradient of sin(pi) is", grad_sine(np.pi))

Gradient of sin(pi) is -0.9998995297042174


In [8]:
def sum_of_squares(x):
    return np.sum(x**2)

In [9]:
sum_of_squares_dx = grad(sum_of_squares)

x = np.asarray([1.0, 2.0, 3.0, 4.0])

var1 = sum_of_squares_dx(x)
var2 = sum_of_squares_dx(x)
print(sum_of_squares(x))

print(sum_of_squares_dx(x))

30.0
[2. 4. 6. 8.]


In [11]:
def sum_squared_error(x, y):
    return np.sum((x-y)**2)

sum_squared_error_dx = grad(sum_squared_error)

y = np.asarray([1.1, 2.1, 3.1, 4.1])

print(sum_squared_error_dx(x, y))

[-0.2 -0.2 -0.2 -0.2]


In [14]:
sum_sq_error_dxdy = grad(sum_squared_error,(0,1))

In [20]:
np.asarray((sum_sq_error_dxdy(x,y)))

array([[-0.2, -0.2, -0.2, -0.2],
       [ 0.2,  0.2,  0.2,  0.2]])

In [26]:
mat = np.asarray([[1,2],[42,2]])

In [27]:
mat[1][1] = 2

In [28]:
type(mat)

numpy.ndarray

In [29]:
import autograd.numpy as np
from autograd.scipy.integrate import odeint
from autograd import grad
from autograd.builtins import tuple

In [37]:
# var =2.3

In [74]:
def intFunc(x):
    def func(y, t, alpha):
        return -np.sin(alpha * t)
    y0 = 0.
    t = np.linspace(0., 1., 100)
    y = odeint(func, y0, t, tuple([x]))[-1]
    return y



In [75]:
# intFunc(4)

In [76]:
import matplotlib.pyplot as plt

In [78]:
# plt.plot(np.linspace(0., 1., 100),intFunc(1))

In [79]:
# print(intFunc(0.5))
intFuncGrad = grad(intFunc)

In [84]:
vect_intFuncGrad = np.vectorize(intFuncGrad)

In [91]:
x = np.array([1.0,2.4,2.1])
x

array([1. , 2.4, 2.1])

In [93]:
vect_intFuncGrad(x)

array([-0.38177193,  0.02018775, -0.06981695])

In [94]:
intFuncGrad(x)

RuntimeError: The size of the array returned by func (3) does not match the size of y0 (1).