In [16]:
import jax

In [17]:
import jax.numpy as jnp

In [18]:
import numpy as np

In [19]:
x = jnp.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [20]:
x

DeviceArray([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [21]:
def sum_of_squares(x):
    return jnp.sum(x**2)

In [22]:
sum_of_squares_dx = jax.grad(sum_of_squares)

x = np.asarray([1.0, 2.0, 3.0, 4.0])

var1 = sum_of_squares_dx(x)
var2 = sum_of_squares_dx(x)
print(sum_of_squares(x))

print(sum_of_squares_dx(x))

30.0
[2. 4. 6. 8.]


In [23]:
var1

DeviceArray([2., 4., 6., 8.], dtype=float32)

In [24]:
np_var1 = np.asarray(var1)

In [25]:
np_var1

array([2., 4., 6., 8.], dtype=float32)

In [26]:
def sum_squared_error(x, y):
    return np.sum((x-y)**2)

sum_squared_error_dx = jax.grad(sum_squared_error)

y = np.asarray([1.1, 2.1, 3.1, 4.1])

print(sum_squared_error_dx(x, y))

[-0.20000005 -0.19999981 -0.19999981 -0.19999981]


In [27]:
2*(2-2.1)

-0.20000000000000018

In [28]:
sum_sq_error_dxdy = jax.grad(sum_squared_error,argnums=(0,1))

In [29]:
sum_sq_error_dxdy(x,y)

(DeviceArray([-0.20000005, -0.19999981, -0.19999981, -0.19999981], dtype=float32),
 DeviceArray([0.20000005, 0.19999981, 0.19999981, 0.19999981], dtype=float32))

In [16]:
jax.value_and_grad(sum_squared_error)(x, y)

(DeviceArray(0.03999995, dtype=float32),
 DeviceArray([-0.20000005, -0.19999981, -0.19999981, -0.19999981], dtype=float32))

In [17]:
sum_squared_error(x,y)

DeviceArray(0.03999995, dtype=float32)